import Link from 'next/link'
import type { Metadata } from 'next'
import { Header } from '../components/layout/Header'
import { Anchor, AlertTriangle } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service - Helmwise',
  description: 'Helmwise Terms of Service. Important disclaimers regarding the use of AI-powered passage planning tools for maritime navigation.',
}

export default function TermsPage() {
  const lastUpdated = 'February 13, 2026'

  return (
    <>
      <Header />

      <div className="min-h-screen px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <h1 className="font-display text-4xl mb-2">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: {lastUpdated}</p>

          {/* Critical Safety Disclaimer Banner */}
          <div className="bg-destructive/10 border-2 border-destructive/30 rounded-lg p-6 mb-12">
            <div className="flex items-start gap-4">
              <AlertTriangle className="h-8 w-8 text-destructive flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-bold text-destructive mb-3">
                  CRITICAL SAFETY DISCLAIMER
                </h2>
                <p className="font-semibold mb-2">
                  HELMWISE IS A SUPPLEMENTARY PLANNING TOOL ONLY. IT IS NOT A SUBSTITUTE FOR PROPER SEAMANSHIP, PROFESSIONAL NAVIGATION, OFFICIAL CHART WORK, OR SOUND MARINER JUDGMENT.
                </p>
                <p className="text-sm text-muted-foreground">
                  All passage plans, weather data, tidal predictions, safety assessments, and recommendations generated by Helmwise are provided for informational and planning assistance purposes only. Mariners must independently verify all information against official sources and exercise their own professional judgment before and during any voyage. You assume full responsibility for all navigation decisions.
                </p>
              </div>
            </div>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-10">

            {/* 1. Acceptance */}
            <section>
              <h2 className="font-display text-2xl mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using Helmwise (the &ldquo;Service&rdquo;), operated by Helmwise (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you must not use the Service. We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.
              </p>
            </section>

            {/* 2. Service Description */}
            <section>
              <h2 className="font-display text-2xl mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground">
                Helmwise is an AI-powered passage planning platform that aggregates data from various third-party sources (including but not limited to NOAA, National Weather Service, OpenWeather, and NDBC buoy networks) and processes it through specialized AI agents to generate passage plans, weather analyses, tidal predictions, safety assessments, and route recommendations.
              </p>
              <p className="text-muted-foreground mt-4">
                <strong>The Service is intended solely as a supplementary planning aid.</strong> It is designed to assist mariners in their passage planning process, not to replace any aspect of professional navigation, official chart work, seamanship, or mariner judgment.
              </p>
            </section>

            {/* 3. CRITICAL NAVIGATION DISCLAIMERS */}
            <section>
              <h2 className="font-display text-2xl mb-4">3. Navigation and Safety Disclaimers</h2>
              <p className="text-muted-foreground font-semibold">
                THIS SECTION CONTAINS CRITICAL SAFETY INFORMATION. PLEASE READ IT CAREFULLY.
              </p>

              <h3 className="text-lg font-semibold mt-6 mb-3">3.1 Not a Substitute for Professional Navigation</h3>
              <p className="text-muted-foreground">
                Helmwise does not replace and must not be used as a substitute for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Official nautical charts and publications</li>
                <li>Professional weather forecasting services</li>
                <li>Certified navigation equipment and instruments</li>
                <li>Proper seamanship training and certification</li>
                <li>Coast Guard, harbor authority, or port authority guidance</li>
                <li>Notice to Mariners and official navigation warnings</li>
                <li>Your own visual observations, situational awareness, and judgment</li>
                <li>Any requirements under COLREGS, SOLAS, or applicable maritime law</li>
              </ul>

              <h3 className="text-lg font-semibold mt-6 mb-3">3.2 AI-Generated Content May Contain Errors</h3>
              <p className="text-muted-foreground">
                All data, recommendations, and passage plans generated by Helmwise are produced by artificial intelligence systems and automated data processing. These outputs may contain errors, inaccuracies, omissions, or outdated information. Specifically:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Weather forecasts are inherently uncertain and may be incorrect</li>
                <li>Tidal predictions are approximations and may not reflect actual conditions</li>
                <li>Route calculations may not account for all hazards, obstructions, or local conditions</li>
                <li>Port and marina information may be outdated or incomplete</li>
                <li>Safety assessments may fail to identify all relevant risks</li>
                <li>Depth data and clearance calculations are estimates and should never be solely relied upon</li>
                <li>Restricted area boundaries and regulations may change without notice</li>
              </ul>

              <h3 className="text-lg font-semibold mt-6 mb-3">3.3 Data Source Limitations</h3>
              <p className="text-muted-foreground">
                Helmwise aggregates data from third-party sources over which we have no control. These data sources may experience outages, delays, errors, or discontinuation at any time without notice. We do not guarantee the accuracy, completeness, timeliness, or availability of any third-party data. When data sources conflict, the Service attempts to present worst-case scenarios, but this process is automated and may not always function correctly.
              </p>

              <h3 className="text-lg font-semibold mt-6 mb-3">3.4 User Responsibility</h3>
              <p className="text-muted-foreground">
                <strong>You, as the mariner and master of your vessel, bear sole and complete responsibility for:</strong>
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>All navigation decisions before, during, and after any voyage</li>
                <li>Independently verifying all information provided by the Service against official sources</li>
                <li>Conducting your own thorough passage planning using proper charts and publications</li>
                <li>Monitoring actual weather and sea conditions and adjusting plans accordingly</li>
                <li>Ensuring your vessel is seaworthy and properly equipped for the intended voyage</li>
                <li>Maintaining proper qualifications and certifications for your intended voyage</li>
                <li>Compliance with all applicable maritime laws, regulations, and rules of the road</li>
                <li>The safety of your vessel, crew, passengers, and cargo</li>
              </ul>
            </section>

            {/* 4. Limitation of Liability */}
            <section>
              <h2 className="font-display text-2xl mb-4">4. Limitation of Liability</h2>

              <h3 className="text-lg font-semibold mt-6 mb-3">4.1 Disclaimer of Warranties</h3>
              <p className="text-muted-foreground">
                THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, RELIABILITY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE MAKE NO WARRANTY REGARDING THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICE.
              </p>

              <h3 className="text-lg font-semibold mt-6 mb-3">4.2 Limitation of Liability</h3>
              <p className="text-muted-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HELMWISE, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Loss of life, personal injury, or bodily harm</li>
                <li>Loss of or damage to vessels, cargo, or property</li>
                <li>Environmental damage or pollution incidents</li>
                <li>Grounding, collision, capsizing, or any maritime casualty</li>
                <li>Search and rescue costs</li>
                <li>Salvage claims</li>
                <li>Loss of profits, data, or business opportunities</li>
                <li>Any other losses arising from the use of or inability to use the Service</li>
              </ul>
              <p className="text-muted-foreground mt-4">
                This limitation applies regardless of the theory of liability (contract, tort, negligence, strict liability, or otherwise), even if we have been advised of the possibility of such damages.
              </p>

              <h3 className="text-lg font-semibold mt-6 mb-3">4.3 Maximum Liability</h3>
              <p className="text-muted-foreground">
                In no event shall our total aggregate liability to you exceed the amount you have paid to us for the Service in the twelve (12) months preceding the event giving rise to the claim, or one hundred US dollars ($100), whichever is greater.
              </p>
            </section>

            {/* 5. Indemnification */}
            <section>
              <h2 className="font-display text-2xl mb-4">5. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify, defend, and hold harmless Helmwise, its officers, directors, employees, agents, partners, and licensors from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or relating to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>Your use of or reliance on the Service</li>
                <li>Any navigation decisions made using information from the Service</li>
                <li>Any maritime incident, casualty, or accident occurring during or after a voyage planned with the assistance of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any applicable maritime law, regulation, or rule</li>
                <li>Any claim by a third party arising from your use of the Service</li>
              </ul>
            </section>

            {/* 6. Assumption of Risk */}
            <section>
              <h2 className="font-display text-2xl mb-4">6. Assumption of Risk</h2>
              <p className="text-muted-foreground">
                Maritime navigation is inherently dangerous. By using the Service, you expressly acknowledge and assume all risks associated with maritime navigation, including but not limited to risks of adverse weather, sea conditions, equipment failure, navigational hazards, and human error. You understand that the Service cannot eliminate or fully mitigate these risks, and you agree that your use of the Service is entirely at your own risk.
              </p>
              <p className="text-muted-foreground mt-4">
                You represent and warrant that you possess adequate training, experience, qualifications, and certifications for the voyages you plan using the Service, and that you will not undertake any voyage for which you or your vessel are not adequately prepared, regardless of any assessment provided by the Service.
              </p>
            </section>

            {/* 7. User Accounts */}
            <section>
              <h2 className="font-display text-2xl mb-4">7. User Accounts and Subscriptions</h2>
              <p className="text-muted-foreground">
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use. We reserve the right to suspend or terminate accounts at our discretion.
              </p>
              <p className="text-muted-foreground mt-4">
                Paid subscriptions are billed in advance on a monthly or annual basis. You may cancel at any time, and access will continue through the end of your current billing period. Refunds are provided at our sole discretion. All prices are in US dollars and are subject to change with 30 days&apos; notice.
              </p>
            </section>

            {/* 8. Intellectual Property */}
            <section>
              <h2 className="font-display text-2xl mb-4">8. Intellectual Property</h2>
              <p className="text-muted-foreground">
                The Service, including all software, content, design, and documentation, is owned by Helmwise and protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms. Passage plans and exports generated for your use are yours to keep and use.
              </p>
            </section>

            {/* 9. Privacy */}
            <section>
              <h2 className="font-display text-2xl mb-4">9. Privacy and Data</h2>
              <p className="text-muted-foreground">
                Your use of the Service is also governed by our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>. We collect route data, vessel information, and usage analytics to improve the Service. We do not sell personal data to third parties. Voyage data may be retained for safety audit purposes.
              </p>
            </section>

            {/* 10. Prohibited Uses */}
            <section>
              <h2 className="font-display text-2xl mb-4">10. Prohibited Uses</h2>
              <p className="text-muted-foreground">
                You agree not to use the Service:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-2">
                <li>As the sole basis for any navigation decision</li>
                <li>For commercial shipping operations requiring certified voyage planning systems</li>
                <li>In any manner that violates applicable maritime law or regulations</li>
                <li>To plan voyages beyond your qualifications, experience, or vessel capabilities</li>
                <li>To reverse engineer, decompile, or disassemble the Service</li>
                <li>To attempt to gain unauthorized access to the Service or its infrastructure</li>
                <li>To resell or redistribute the Service without our written consent</li>
              </ul>
            </section>

            {/* 11. Service Availability */}
            <section>
              <h2 className="font-display text-2xl mb-4">11. Service Availability</h2>
              <p className="text-muted-foreground">
                We do not guarantee continuous, uninterrupted access to the Service. The Service may be unavailable due to maintenance, updates, or circumstances beyond our control, including data source outages. You should never depend on the availability of the Service during a voyage. Always have alternative passage planning resources available.
              </p>
            </section>

            {/* 12. Termination */}
            <section>
              <h2 className="font-display text-2xl mb-4">12. Termination</h2>
              <p className="text-muted-foreground">
                We may terminate or suspend your access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately. Sections 3 through 6 (disclaimers, limitation of liability, indemnification, and assumption of risk) shall survive termination.
              </p>
            </section>

            {/* 13. Governing Law */}
            <section>
              <h2 className="font-display text-2xl mb-4">13. Governing Law and Disputes</h2>
              <p className="text-muted-foreground">
                These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or the use of the Service shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. You agree to waive any right to a jury trial or to participate in a class action.
              </p>
            </section>

            {/* 14. Severability */}
            <section>
              <h2 className="font-display text-2xl mb-4">14. Severability</h2>
              <p className="text-muted-foreground">
                If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.
              </p>
            </section>

            {/* 15. Entire Agreement */}
            <section>
              <h2 className="font-display text-2xl mb-4">15. Entire Agreement</h2>
              <p className="text-muted-foreground">
                These Terms, together with the Privacy Policy, constitute the entire agreement between you and Helmwise regarding the use of the Service and supersede all prior agreements and understandings.
              </p>
            </section>

            {/* 16. Contact */}
            <section>
              <h2 className="font-display text-2xl mb-4">16. Contact</h2>
              <p className="text-muted-foreground">
                For questions about these Terms, contact us at{' '}
                <a href="mailto:legal@helmwise.co" className="text-primary hover:underline">legal@helmwise.co</a>.
              </p>
            </section>

          </div>

          {/* Final Safety Reminder */}
          <div className="mt-16 bg-destructive/10 border-2 border-destructive/30 rounded-lg p-6">
            <div className="flex items-start gap-4">
              <AlertTriangle className="h-6 w-6 text-destructive flex-shrink-0 mt-1" />
              <div>
                <p className="font-semibold text-sm">
                  REMEMBER: Helmwise is a supplementary planning tool. Always rely on your own seamanship, official charts and publications, certified instruments, and professional judgment. The safety of your vessel, crew, and passengers is your responsibility alone.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="px-4 py-12 sm:px-6 lg:px-8 border-t border-border">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <Anchor className="h-5 w-5 text-primary" />
              <span className="font-display font-bold">Helmwise</span>
            </div>
            <p className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} Helmwise. All rights reserved.
            </p>
            <div className="flex gap-6 text-sm text-muted-foreground">
              <Link href="/about" className="hover:text-primary transition-colors">About</Link>
              <Link href="/privacy" className="hover:text-primary transition-colors">Privacy</Link>
            </div>
          </div>
        </div>
      </footer>
    </>
  )
}
