import type { PassageExport } from "../../types/shared";

// ============================================================================
// Garmin-flavored GPX
//
// Garmin chartplotters (GPSMAP / ECHOMAP / EchoMAP UHD) read standard GPX
// for routes — they DO NOT need the FIT binary format (FIT is for fitness
// activities like cycling, not for navigation routes).
//
// What Garmin's BaseCamp / MapSource produces, and what their chartplotters
// render best, is GPX with the `gpxx` extension namespace
// (http://www.garmin.com/xmlschemas/GpxExtensions/v3). The key things we
// emit:
//
//   - xmlns:gpxx declaration on the root <gpx> element
//   - <extensions><gpxx:WaypointExtension><gpxx:DisplayMode>...
//   - <sym> values from Garmin's icon set ("Anchor", "Flag, Green", etc.)
//
// Plain GPX (no gpxx) also works on Garmin plotters — this just makes the
// icons render nicely instead of falling back to a generic dot.
// ============================================================================

interface GarminGpxOptions {
  /** Vessel name shown in metadata. */
  vesselName?: string;
}

const GARMIN_NS = "http://www.garmin.com/xmlschemas/GpxExtensions/v3";

export function passageToGarminGPX(
  passage: PassageExport,
  options: GarminGpxOptions = {},
): string {
  const timestamp = new Date().toISOString();
  const points = collectPoints(passage);
  if (points.length === 0) {
    throw new Error(
      "Cannot export to Garmin GPX: passage has no usable coordinates.",
    );
  }

  const waypointsXml = points
    .map((p, idx) => {
      const sym = pickGarminSymbol(p.role);
      const dispMode = p.role === "waypoint" ? "SymbolOnly" : "SymbolAndName";
      return `  <wpt lat="${p.lat.toFixed(6)}" lon="${p.lon.toFixed(6)}">
    <name>${escapeXml(p.name)}</name>
    <sym>${sym}</sym>
    <type>WPT</type>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="${GARMIN_NS}">
        <gpxx:DisplayMode>${dispMode}</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>`;
    })
    .join("\n");

  const routePoints = points
    .map(
      (p) => `    <rtept lat="${p.lat.toFixed(6)}" lon="${p.lon.toFixed(6)}">
      <name>${escapeXml(p.name)}</name>
      <sym>${pickGarminSymbol(p.role)}</sym>
    </rtept>`,
    )
    .join("\n");

  const vesselDesc = options.vesselName
    ? `Vessel: ${escapeXml(options.vesselName)}. `
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
     creator="Helmwise - helmwise.co"
     xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:gpxx="${GARMIN_NS}"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${escapeXml(passage.name ?? "Passage")}</name>
    <desc>${vesselDesc}Garmin-flavored GPX generated by Helmwise.</desc>
    <time>${timestamp}</time>
  </metadata>
${waypointsXml}
  <rte>
    <name>${escapeXml(passage.name ?? "Passage")}</name>
${routePoints}
  </rte>
</gpx>
`;
}

type PointRole = "departure" | "destination" | "waypoint";
interface CollectedPoint {
  name: string;
  lat: number;
  lon: number;
  role: PointRole;
}

function collectPoints(passage: PassageExport): CollectedPoint[] {
  const out: CollectedPoint[] = [];
  const dep = endpointToPoint(passage.departure, "Departure", "departure");
  if (dep) out.push(dep);
  for (const wp of passage.waypoints ?? []) {
    const p = waypointToPoint(wp);
    if (p) out.push(p);
  }
  const dest = endpointToPoint(
    passage.destination,
    "Destination",
    "destination",
  );
  if (dest) out.push(dest);
  return out;
}

function endpointToPoint(
  ep: PassageExport["departure"] | undefined,
  fallbackName: string,
  role: PointRole,
): CollectedPoint | null {
  if (!ep) return null;
  const coords = toLatLon(
    ep.coordinates?.lat ?? ep.latitude,
    ep.coordinates?.lng ?? ep.longitude,
  );
  if (!coords) return null;
  return { name: ep.name ?? fallbackName, ...coords, role };
}

function waypointToPoint(
  wp: NonNullable<PassageExport["waypoints"]>[number],
): CollectedPoint | null {
  const coords = toLatLon(
    wp.coordinates?.lat ?? wp.latitude,
    wp.coordinates?.lng ?? wp.longitude,
  );
  if (!coords) return null;
  return { name: wp.name ?? "Waypoint", ...coords, role: "waypoint" };
}

// Garmin Marine icon set names (BaseCamp-compatible).
function pickGarminSymbol(role: PointRole): string {
  switch (role) {
    case "departure":
      return "Flag, Blue";
    case "destination":
      return "Anchor";
    case "waypoint":
      return "Waypoint";
  }
}

function toLatLon(
  lat: unknown,
  lon: unknown,
): { lat: number; lon: number } | null {
  if (
    typeof lat === "number" &&
    typeof lon === "number" &&
    Number.isFinite(lat) &&
    Number.isFinite(lon) &&
    lat >= -90 &&
    lat <= 90 &&
    lon >= -180 &&
    lon <= 180
  ) {
    return { lat, lon };
  }
  return null;
}

function escapeXml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
