import type { PassageExport } from "../../types/shared";

// ============================================================================
// OpenCPN-flavored GPX
//
// OpenCPN reads standard GPX with its own `opencpn` extension namespace
// (http://www.opencpn.org). The extensions let users see:
//
//   - A stable GUID per waypoint (so re-imports replace, not duplicate)
//   - Route color and width hints on the chart
//   - Per-waypoint description text
//
// Plain GPX also imports fine — these extensions only enhance the
// presentation. We use deterministic GUIDs derived from the passage name +
// waypoint index so re-exports produce the same identifiers (and re-imports
// update in place rather than appending duplicates).
// ============================================================================

interface OpenCPNGpxOptions {
  /** Hex color for the route line, e.g. "#0EA5E9". OpenCPN defaults to
   *  a generic blue if omitted. */
  routeColor?: string;
  /** Route line width 1..8. Defaults to 2 (medium). */
  routeWidth?: number;
}

const OPENCPN_NS = "http://www.opencpn.org";

export function passageToOpenCPNGPX(
  passage: PassageExport,
  options: OpenCPNGpxOptions = {},
): string {
  const timestamp = new Date().toISOString();
  const points = collectPoints(passage);
  if (points.length === 0) {
    throw new Error(
      "Cannot export to OpenCPN GPX: passage has no usable coordinates.",
    );
  }

  const routeColor = options.routeColor ?? "#0EA5E9";
  const routeWidth = Math.min(8, Math.max(1, options.routeWidth ?? 2));
  const routeName = passage.name ?? "Passage";
  const routeGuid = stableGuid(`route:${routeName}`);

  const waypointsXml = points
    .map(
      (p, idx) => `  <wpt lat="${p.lat.toFixed(6)}" lon="${p.lon.toFixed(6)}">
    <name>${escapeXml(p.name)}</name>
    <sym>${pickSym(p.role)}</sym>
    <type>WPT</type>
    <extensions>
      <opencpn:guid>${stableGuid(`wpt:${routeName}:${idx}`)}</opencpn:guid>
      <opencpn:viz>1</opencpn:viz>
      <opencpn:viz_name>1</opencpn:viz_name>
    </extensions>
  </wpt>`,
    )
    .join("\n");

  const routePoints = points
    .map(
      (
        p,
        idx,
      ) => `    <rtept lat="${p.lat.toFixed(6)}" lon="${p.lon.toFixed(6)}">
      <name>${escapeXml(p.name)}</name>
      <sym>${pickSym(p.role)}</sym>
      <extensions>
        <opencpn:guid>${stableGuid(`rtept:${routeName}:${idx}`)}</opencpn:guid>
      </extensions>
    </rtept>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
     creator="Helmwise - helmwise.co"
     xmlns="http://www.topografix.com/GPX/1/1"
     xmlns:opencpn="${OPENCPN_NS}"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${escapeXml(routeName)}</name>
    <desc>OpenCPN-flavored GPX generated by Helmwise.</desc>
    <time>${timestamp}</time>
  </metadata>
${waypointsXml}
  <rte>
    <name>${escapeXml(routeName)}</name>
    <extensions>
      <opencpn:guid>${routeGuid}</opencpn:guid>
      <opencpn:viz>1</opencpn:viz>
      <opencpn:start>${escapeXml(points[0].name)}</opencpn:start>
      <opencpn:end>${escapeXml(points[points.length - 1].name)}</opencpn:end>
      <opencpn:style>
        <opencpn:color>${routeColor}</opencpn:color>
        <opencpn:width>${routeWidth}</opencpn:width>
      </opencpn:style>
    </extensions>
${routePoints}
  </rte>
</gpx>
`;
}

type PointRole = "departure" | "destination" | "waypoint";
interface CollectedPoint {
  name: string;
  lat: number;
  lon: number;
  role: PointRole;
}

function collectPoints(passage: PassageExport): CollectedPoint[] {
  const out: CollectedPoint[] = [];
  const dep = endpointToPoint(passage.departure, "Departure", "departure");
  if (dep) out.push(dep);
  for (const wp of passage.waypoints ?? []) {
    const p = waypointToPoint(wp);
    if (p) out.push(p);
  }
  const dest = endpointToPoint(
    passage.destination,
    "Destination",
    "destination",
  );
  if (dest) out.push(dest);
  return out;
}

function endpointToPoint(
  ep: PassageExport["departure"] | undefined,
  fallbackName: string,
  role: PointRole,
): CollectedPoint | null {
  if (!ep) return null;
  const coords = toLatLon(
    ep.coordinates?.lat ?? ep.latitude,
    ep.coordinates?.lng ?? ep.longitude,
  );
  if (!coords) return null;
  return { name: ep.name ?? fallbackName, ...coords, role };
}

function waypointToPoint(
  wp: NonNullable<PassageExport["waypoints"]>[number],
): CollectedPoint | null {
  const coords = toLatLon(
    wp.coordinates?.lat ?? wp.latitude,
    wp.coordinates?.lng ?? wp.longitude,
  );
  if (!coords) return null;
  return { name: wp.name ?? "Waypoint", ...coords, role: "waypoint" };
}

function pickSym(role: PointRole): string {
  switch (role) {
    case "departure":
      return "Marks";
    case "destination":
      return "Anchorage";
    case "waypoint":
      return "Empty";
  }
}

// Deterministic GUID derived from a stable seed string. Not cryptographically
// secure — just gives the same UUID-shaped string for the same input across
// re-exports so OpenCPN replaces rather than duplicates on re-import.
function stableGuid(seed: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  const hex = h.toString(16).padStart(8, "0");
  return `${hex}-${hex.slice(0, 4)}-4${hex.slice(1, 4)}-${hex.slice(0, 4)}-${hex}${hex.slice(0, 4)}`;
}

function toLatLon(
  lat: unknown,
  lon: unknown,
): { lat: number; lon: number } | null {
  if (
    typeof lat === "number" &&
    typeof lon === "number" &&
    Number.isFinite(lat) &&
    Number.isFinite(lon) &&
    lat >= -90 &&
    lat <= 90 &&
    lon >= -180 &&
    lon <= 180
  ) {
    return { lat, lon };
  }
  return null;
}

function escapeXml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
